version: '3.8'

services:
  app:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "go build -o main && ./main"
